### ISSUE TITLE
URL 404 for Zabbix Agent 4.0.17

### ISSUE THREAD

**Issue by louiseunice** [zabbix/zabbix-agent-chocolatey#25]
the right URL should be https://cdn.zabbix.com/zabbix/binaries/stable/4.0/4.0.17/zabbix_agent-4.0.17-windows-amd64-openssl.zip while the chocolatey use https://www.zabbix.com/downloads/4.0.17/zabbix_agent-4.0.17-windows-amd64-openssl.zip which is not accessible

**Comment by KakersUK** [comment]
Looks like the Zabbix team have moved over to using a CDN. I've updated the URLs for the future and manually pushed the new versions to the Chocolatey Repo. It'll take some time for the code verification on their part but should hopefully be resolved in a couple of hours.

**Comment by louiseunice** [comment]
How can I know their repo will be refreshed. I tried, still failed.

**Comment by KakersUK** [comment]
The version number will be slightly different as it's a fix for an existing version. 

Examples:

```
choco install zabbix-agent.install --version=4.0.27.20201207
```
Or 
```
choco install zabbix-agent --version=4.0.27.20201207
```
